// Sample content for the kit. Song titles and artists are placeholders.
window.KIT = {
  artists: [
    { name: 'Talking Heads', count: 8, upcoming: true },
    { name: 'Fleetwood Mac', count: 12, starred: true },
    { name: 'Whitney Houston', count: 15 },
    { name: 'Neil Diamond', count: 9 },
    { name: 'Journey', count: 6, starred: true },
    { name: 'Dolly Parton', count: 11 },
    { name: 'ABBA', count: 14 },
    { name: 'Prince', count: 10 },
    { name: 'Stevie Wonder', count: 13 },
  ],
  songs: [
    { title: 'Once in a Lifetime', artist: 'Talking Heads', tags: ['rock', '80s'], duration: '4:19', stars: 4, upcoming: true },
    { title: 'This Must Be the Place', artist: 'Talking Heads', tags: ['rock'], duration: '4:56', stars: 2 },
    { title: 'Psycho Killer', artist: 'Talking Heads', tags: ['rock', '70s'], duration: '4:22', played: true, stars: 1 },
    { title: 'Burning Down the House', artist: 'Talking Heads', tags: ['rock', '80s'], duration: '3:38' },
    { title: 'Dreams', artist: 'Fleetwood Mac', tags: ['rock', '70s'], duration: '4:14', stars: 3, starred: true },
    { title: 'Go Your Own Way', artist: 'Fleetwood Mac', tags: ['rock', '70s'], duration: '3:38', stars: 1 },
    { title: 'I Wanna Dance with Somebody', artist: 'Whitney Houston', tags: ['pop', '80s'], duration: '4:52', stars: 6 },
    { title: 'Sweet Caroline', artist: 'Neil Diamond', tags: ['pop', '60s'], duration: '3:21', stars: 9, played: true },
    { title: "Don't Stop Believin'", artist: 'Journey', tags: ['rock', '80s'], duration: '4:11', stars: 7, starred: true },
    { title: 'Jolene', artist: 'Dolly Parton', tags: ['country', '70s'], duration: '2:41', stars: 2 },
    { title: 'Dancing Queen', artist: 'ABBA', tags: ['pop', '70s'], duration: '3:51', stars: 5 },
    { title: 'Kiss', artist: 'Prince', tags: ['funk', '80s'], duration: '3:46' },
  ],
  facets: ['rock', 'pop', '80s', 'belter'],
  queue: [
    { title: 'Dreams', artist: 'Fleetwood Mac', singer: 'Dana', current: true, pct: 38, starred: true, starCount: 3 },
    { title: 'Once in a Lifetime', artist: 'Talking Heads', singer: 'You', owner: true, wait: '4 min', upcoming: true, starCount: 4 },
    { title: 'Jolene', artist: 'Dolly Parton', singer: 'Priya', wait: '8 min', upcoming: true, starCount: 2 },
    { title: 'Kiss', artist: 'Prince', singer: 'Sam', wait: '12 min', upcoming: true },
    { title: 'Dancing Queen', artist: 'ABBA', singer: 'You', owner: true, wait: '16 min', upcoming: true, starCount: 5 },
  ],
  history: [
    { title: 'Sweet Caroline', artist: 'Neil Diamond', singer: 'Sam', played: true, starCount: 9 },
    { title: 'Psycho Killer', artist: 'Talking Heads', singer: 'Dana', played: true, starCount: 1 },
  ],
  rooms: [
    { name: 'Living Room', status: 'open', users: 6, created: 'Aug 29' },
    { name: 'Back Patio', status: 'open', users: 2, created: 'Aug 29' },
    { name: 'New Year 2026', status: 'closed', users: 0, created: 'Dec 31' },
  ],
  users: [
    { username: 'dana', name: 'Dana', role: 'standard', joined: 'Aug 29' },
    { username: 'sam', name: 'Sam', role: 'guest', joined: 'Aug 29' },
    { username: 'priya', name: 'Priya', role: 'standard', joined: 'Aug 28' },
    { username: 'host', name: 'Host', role: 'admin', joined: 'Jan 4' },
  ],
  sung: [
    { title: 'Sweet Caroline', artist: 'Neil Diamond', date: 'Aug 29' },
    { title: 'Africa', artist: 'Toto', date: 'Aug 15' },
    { title: 'Total Eclipse of the Heart', artist: 'Bonnie Tyler', date: 'Jul 4' },
  ],
};
